#!/bin/bash
# This is the simple installer script for LamPI
# SHOULD THIS FILE NOT WORK, please make sure to convert from DOS to Unix
# (c) M. Westenberg, 2013-2015
#
# Basically there are 3 types of installation:
#
# 1. The LamPI-master containing the LamPI-daemon, and possibly some sensors incl LamPI-receiver
# 2. A LamPI slave, this is a Raspberry with only sensors or receiver/transmitter but is a slave 
#    of the Master. It does not contain a LamPI-daemon nor a database
# 3. A LamPI-z-way device. This is a Raspberry + Razberry combo acting as a gateway/slave
#    for controlling Z-Wave devices
#
LINUX="y"; export LINUX
WIRING="y"; export WIRING
RRDTOOL="n"; export RRDTOOL
RAZBERRY="n"; export RAZBERRY
CRONTAB="y"; export CRONTAB

# This will be THE directory where LamPI is installed. It is possible to change the install directory.
# But please update the ~/daemon/backend_cfg.php and the ~/www/frontend_cfg.php file to update the new
# location. Also watch the log files as there might be other places where I have hardcoded /home/pi as
# the installation directory.

HOMEDIR="/home/pi"; export HOMEDIR

# -----------------------------------------------------------------------------------------------------
# NOTE: Since WIFI does not work out of the box, this initial setup must be
# done over a network connection. As soon as WIFI works further access
# can be done over WIFI



# -----------------------------------------------------------------------------------------------------
# General Linux bookkeeping and installatation of the latest packages
#
install_linux()
{
	sudo apt-get -q update
	sudo apt-get -q upgrade

	#sudo apt-get -qy install php5
	sudo apt-get -qy install mysql-server
	sudo apt-get -y install mysql-client
	#sudo apt-get -y install php5-mysql
	#sudo apt-get -qy install php5-dev
	#sudo apt-get -qy install php5-pear
	#sudo apt-get -qy install php5-curl
	sudo apt-get -qy install apache2
    sudo apt-get -qy install lm-sensors
	sudo apt-get -y install rrdtool				# We might want the latest version, this is not but it works!
	sudo apt-get -qy install i2c-tools
	sudo apt-get -qy install libpango1.0-dev libxml2-dev
	sudo apt-get -y install phpmyadmin
	sudo apt-get -y install dos2unix

	echo "All LamPI required packages have been installed"
	echo ""
}


# -----------------------------------------------------------------------------------------------------
# Download, Install and build the RazBerry software.
# Only do this if you have a Razberry installed 
#
install_zway()
{
	echo "Starting installation of Z-Way Razberry"
	wget -q -O - http://razberry.zwave.me/install/v2.0.1-rc25 | sudo bash 
}

# -----------------------------------------------------------------------------------------------------
# Download, Install and build the ZigBee RaspBee software.
# Only do this if you have a Raspbee installed 
#
install_raspbee()
{
	cd $HOMEDIR
	sudo apt-get -y install libqt4-core 
    wget http://www.dresden-elektronik.de/rpi/gcfflasher/gcfflasher-latest.deb
    sudo dpkg -i gcfflasher-latest.deb
    
    wget http://www.dresden-elektronik.de/rpi/deconz/deconz-latest.deb
	wget http://www.dresden-elektronik.de/rpi/deconz-dev/deconz-dev-latest.deb
    sudo dpkg -i deconz-latest.deb
    sudo dpkg -i deconz-dev-latest.deb
	sudo apt-get -y install qt4-dev-tools
    git clone https://github.com/dresden-elektronik/deconz-rest-plugin.git

    cd deconz-rest-plugin
    qmake-qt4 && make
    
	# Install the vncserver package 
    sudo apt-get -y install tightvncserver
    
    # Install the Node package
    install_node
    
    # You have to install and run the vncserver in order to be able to access the raspbee
    # console package deCONZ
}

# -----------------------------------------------------------------------------------------------------
# Install the LamPI software from the download server
#
install_lampi()
{
	cd $HOMEDIR

	# The command below might FAIL if the PI-install script is put in $HOMEDIR/scripts and
	# if the $HOMEDIR directory is not empty. For safety we therefore copy to /tmp first.
	#
	rm -rf /tmp/effe
	mkdir /tmp/effe
	git clone git://github.com/platenspeler/LamPI-3.0 /tmp/effe
	printf "Copying LamPI to its destination directory\n"
	( cd /tmp/effe; tar cf - . ) | tar xpf - 
	rm -rf /tmp/effe

	sudo chown -R pi .
	sudo chgrp -R pi .
    
	# ----------------------------------------------------------------
	# Set the apache base directory, replace the standard /var/www directory
	# with the new directory as in $HOMEDIR/www
	#
	echo "editing sites-available"
	sudo sed "s|/var/www|${HOMEDIR}/www|g" /etc/apache2/sites-available/default > /tmp/effe
	sudo mv /etc/apache2/sites-available/default /etc/apache2/sites-available/default.org
	sudo mv /tmp/effe /etc/apache2/sites-available/default
	sudo /etc/init.d/apache2 restart

	# -------------------------------------------------------------
	# Finally, set some LamPI- related directories and permissions
	#
	sudo chown -R pi $HOMEDIR
	sudo chgrp -R pi $HOMEDIR
    
	mkdir $HOMEDIR/daemon
	mkdir -m 775 $HOMEDIR/log; sudo chgrp www-data $HOMEDIR/log
    mkdir -m 775 $HOMEDIR/graphs; sudo chgrp www-data $HOMEDIR/graphs
    mkdir -m 775 $HOMEDIR/rrd/db; sudo chgrp www-data $HOMEDIR/rrd/db
	mkdir -m 755 $HOMEDIR/exe; sudo chown -R root $HOMEDIR/exe; sudo chmod u+s $HOMEDIR/exe/*

	sudo chmod 755 $HOMEDIR/scripts/PI*
    
    # If we do not do this the rrdtool cannot create a database
    sudo chmod 775 $HOMEDIR/rrd/db; sudo chgrp www-data $HOMEDIR/rrd/db

	# --------------------------------------------------------------
	# Fix the .exe directory And build the executables from source directories
    #
	cd $HOMEDIR/receivers/sniffer; make; sudo make install
	cd $HOMEDIR/transmitters/livolo; make ; sudo make install
	cd $HOMEDIR/transmitters/kaku; make; sudo make install
	cd $HOMEDIR/transmitters/lights; make; sudo make install
	cd $HOMEDIR/transmitters/kopou; make; sudo make install    

}

# -----------------------------------------------------------------------------------------------------
# After downloading MySQL, try to configure 
#
install_mysql()
{
isdone=""
    echo ""
    echo "Trying to finish the MySQL installation and configuring"
    echo "Remember this is a simple configuration only"
    echo "---- type <Control C> anytime if you want to quit"
    echo ""
    echo -n "What is the MySQL password of the root user: " ; read ROOTPASSWORD
    echo -n "What is name of the new MySQL database: " ; read DBASENAME
    echo -n "What new User do you like to make: " ; read USERNAME
    echo -n "What password should $USERNAME have: " ; read USERPASSWORD

a=""
while [ "$isdone" != "Y"  ]
do
   echo ""
   echo -n "continue? (Y/N) "
   read a
   if [ "$a" == "Y" ]; then
        isdone="Y"
   elif [ "$a" == "N" ]; then
        exit 1
   fi
done

mysql -u root --password=$ROOTPASSWORD <<EOF
SELECT 'Starting MySQL' AS ' ';
  CREATE DATABASE $DBASENAME;
  USE $DBASENAME;
  SELECT 'Creating database $DBASENAME' AS ' ';
  CREATE USER '$USERNAME'@'localhost' IDENTIFIED BY '$USERPASSWORD';
  GRANT ALL PRIVILEGES ON $DBASENAME.* TO '$USERNAME'@'localhost';
  FLUSH PRIVILEGES;
  SELECT 'Ending MySQL' AS ' ';
  quit
EOF

mysql -u root --password=$ROOTPASSWORD <<EOF
  SELECT 'Databases defined: ' AS ' ';
  SHOW DATABASES;
  SELECT 'Users defined: ' AS ' ';
  SELECT host, user, password FROM mysql.user;
EOF

echo ""
echo "Do not forget to either include the database and user credential in the file ~/config/params.js"
echo "or put them in the ~/.profile file of the pi user"
echo "Do you want me to include the uer data in the ~/.profile file (if not already there)?"

a=""
isdone=""
while [ "$isdone" != "Y"  ]
do
   echo ""
   echo -n "continue? (Y/N) "
   read a
   if [ "$a" == "Y" ]; then
        isdone="Y"
   elif [ "$a" == "N" ]; then
        exit 1
   fi
done

grep "DBHOST" ~/.profile > /dev/null
if [ $? = 0 ]; then
	echo "File ~/.profile already contains database ENV settings"
    echo "No actions taken ..."
else
	echo "DBHOST=\"localhost\"; export DBHOST " >> ~/.profile 
	echo "DBUSER=\"$USERNAME\"; export DBUSER " >> ~/.profile
	echo "DBPASSWD=\"$USERPASSWORD\"; export DBPASSWD " >> ~/.profile
	echo "DBNAME=\"$DBASENAME\"; export DBNAME " >> ~/.profile
fi
}

# -----------------------------------------------------------------------------------------------------
# Download, Install and build the wiringPI library of Gordon
#
install_wiringpi()
{
	echo ""
	echo "Starting installation of Wiring Libraries"
	sudo apt-get install git-core
	if [ -d wiringPi ]; then
		cd wiringPi
		git pull origin
        ./build
	else
		git clone git://git.drogon.net/wiringPi
		cd wiringPi
		./build
	fi
	echo ""
}


# -----------------------------------------------------------------------------------------------------
# Configure MODULES
# Make the w1 bus modules load at system startup
# by adding module in the /etc/modules files
#
setup_modules()
{
	echo 'w1-gpio' | sudo tee --append /etc/modules
	echo 'w1-therm' | sudo tee --append  /etc/modules
	echo 'i2c-bcm2708' | sudo tee --append  /etc/modules
	echo 'i2c-dev' | sudo tee --append  /etc/modules

	# Standard, there are two modules blacklisted in the raspi-blacklist.conf
	# file as found the modprobe.d directory. Just comment these blacklisted
	# modules out.
	#
	sudo sed 's|blacklist|#blacklist|g' /etc/modprobe.d/raspi-blacklist.conf > /tmp/effe
	sudo mv /etc/modprobe.d/raspi-blacklist.conf /etc/modprobe.d/raspi-blacklist.conf.org
	sudo mv /tmp/effe /etc/modprobe.d/raspi-blacklist.conf
    #
    # Patch to make sure that the wifi adapter does not go to sleep
    echo "options 8192cu rtw_power_mgnt=0 rtw_enusbss=0" | sudo tee --append   /etc/modprobe.d/8192cu.conf
    
    # Enabling devicetree support
    # Make sure that the GPIO pin of the w1 sensor (ds18b20) matches with your setup
    echo 'dtoverlay=w1-gpio,gpiopin=4'  | sudo tee --append  /boot/config.txt
    echo 'dtparam=i2c1=on'    | sudo tee --append  /boot/config.txt
	echo 'dtparam=i2c_arm=on' | sudo tee --append  /boot/config.txt
    
    sudo modprobe w1-gpio
	sudo modprobe w1-therm
    sudo modprobe i2c_dev
    sudo modprobe i2c_bcm2708
    
    # Grant access to normal users with the usemod command
    sudo usermod -a -G i2c pi
}


# -----------------------------------------------------------------------------------------------------
# Setup the crontab so that daemon and receiver are enabled.
# NOTE: STandard we enable all types of devices EXCEPT the dht22/rht-03.
# Thsi is because this device requires extensive polling or interrupt handling which
# makes it not suitable for larger installations. Use the sht-021 device (i2c bus) instead!
#
setup_cron()
{
	echo "Setting up crontab"
	crontab -u pi -l | grep "PI-node" > /dev/null
	if [ $? = 0 ]; then
		echo "-- Crontab already contains LamPI PI-node commands"
	else
		echo "-- Crontab adding LamPI commands"
		crontab -u pi -l > /tmp/effe
		
        // MASTER
        if [ "$1" == "-m" ]; then
			echo "Setting up contab with PI-run for manager"
            echo "*   * * * * . $HOME/.profile; cd $HOMEDIR/scripts && sh ./PI-node > /dev/null 2>&1"	>> /tmp/effe
			echo "*   * * * * cd $HOMEDIR/scripts && sh ./PI-rcv > /dev/null 2>&1"	>> /tmp/effe
			echo "0   2 * * * cd $HOMEDIR/scripts && sh ./PI-log > /dev/null 2>&1"	>> /tmp/effe
			echo "*/2 * * * * cd $HOMEDIR/scripts && sh ./PI-1w > /dev/null 2>&1"	>> /tmp/effe
            #Leave out support for DHT11 and DHT22 by default. Cpu intensive!
			#echo "*/5 * * * * cd $HOMEDIR/scripts && sh ./PI-rht03 > /dev/null 2>&1"	>> /tmp/effe
			echo "*/3 * * * * cd $HOMEDIR/scripts && sh ./PI-i2c > /dev/null 2>&1"	>> /tmp/effe
            # Uncomment the net line for the node managing P1 sensor
			#echo "*   * * * * cd $HOMEDIR/scripts && sh ./PI-energy > /dev/null 2>&1"	>> /tmp/effe
            # Next line is to set transmitter in a stable state (at startup or error)
            echo "*/2 * * * * cd /home/pi/exe && sh ./kaku -g 99 -n 1 1 > /dev/null 2>&1 " >> /tmp/effe
        
        // ZWAVE 
        elif [ "$1" == "-z" ]; then
			echo "Setting up contab for Zway Gateway"
            #echo "*   * * * * . $HOME/.profile; cd $HOMEDIR/scripts && sh ./PI-node	> /dev/null 2>&1"	>> /tmp/effe
			echo "0   2 * * * cd $HOMEDIR/scripts && sh ./PI-log	> /dev/null 2>&1"	>> /tmp/effe
        
        // SLAVE
		else
			echo "Setting up contab for slave"
			echo "*   * * * * cd $HOMEDIR/scripts && sh ./PI-rcv > /dev/null 2>&1"	>> /tmp/effe
			echo "0   2 * * * cd $HOMEDIR/scripts && sh ./PI-log > /dev/null 2>&1"	>> /tmp/effe
			echo "*/2 * * * * cd $HOMEDIR/scripts && sh ./PI-1w > /dev/null 2>&1"	>> /tmp/effe
            #Leave out support for DHT11 and DHT22 by default. Cpu intensive!
			#echo "*/5 * * * * cd $HOMEDIR/scripts && sh ./PI-rht03 > /dev/null 2>&1"	>> /tmp/effe
			echo "*/3 * * * * cd $HOMEDIR/scripts && sh ./PI-i2c > /dev/null 2>&1"	>> /tmp/effe
            #For node with the the P1 energy connector uncomment this line
			#echo "*   * * * * cd $HOMEDIR/scripts && sh ./PI-energy > /dev/null 2>&1"	>> /tmp/effe
            echo "*/2 * * * * cd $HOMEDIR/exe && sh ./kaku -g 99 -n 1 1 > /dev/null 2>&1"	>> /tmp/effe
        fi
        
		crontab -u pi /tmp/effe
	fi
  
	if [ -f /etc/cron.allow ]; then
		cat /etc/cron.allow | grep pi > /dev/null
		if [ $? != 0 ]; then
			sudo echo "pi" >> /etc/at.allow
		fi
	fi
	echo ""
}


# -----------------------------------------------------------------------------------------------------
# Some Wlan Network configuration settings
#
setup_wlan()
{
	sudo grep "network" /etc/wpa_supplicant/wpa_supplicant.conf > /dev/null
	if [ $? = 0 ]; then
		echo "-- wpa_supplicant.conf already contains network clause"
        echo "-- Exiting .."
        sleep 2
        return
	else
    	echo ""
    	echo "Trying to finish the Wifi installation and configuring"
    	echo "Remember this is a simple configuration only."
        echo "We only support PSA-PSK keys at the moment."
    	echo "---- type <Control C> anytime if you want to quit"
		echo ""
		echo -n "What is the SSID of your network: " ; read SSID
		echo -n "What is the network PASS key: " ; read PASSKEY

		a=""
        isdone=""
		while [ "$isdone" != "Y"  ]
			do
				echo ""
				echo -n "continue? (Y/N) "
				read a
				if [ "$a" == "Y" ]; then
					isdone="Y"
				elif [ "$a" == "N" ]; then
				exit 1
			fi
		done
		printf "\nnetwork={\n" | sudo tee --append /etc/wpa_supplicant/wpa_supplicant.conf
		printf "\tssid=\"$SSID\"\n" | sudo tee --append  /etc/wpa_supplicant/wpa_supplicant.conf
		printf "\tscan_ssid=0\n" | sudo tee --append  /etc/wpa_supplicant/wpa_supplicant.conf
		printf "\tpsk=\"$PASSKEY\"\n" | sudo tee --append  /etc/wpa_supplicant/wpa_supplicant.conf
		printf "\tproto=RSN\n" | sudo tee --append  /etc/wpa_supplicant/wpa_supplicant.conf
		printf "\tkey_mgmt=WPA-PSK\n" | sudo tee --append  /etc/wpa_supplicant/wpa_supplicant.conf
		printf "\tpairwise=CCMP\n" | sudo tee --append  /etc/wpa_supplicant/wpa_supplicant.conf
		printf "\tauth_alg=OPEN\n" | sudo tee --append  /etc/wpa_supplicant/wpa_supplicant.conf
		printf "}\n" | sudo tee --append  /etc/wpa_supplicant/wpa_supplicant.conf
	fi
    
	clear

	echo "You may have to edit the wpa_supplicant.conf file and check your Wifi credentials (SSID and Password)"
    echo "Please edit the configuration file and use <CTRL-X> when finished"
	echo "sudo nano /etc/wpa_supplicant/wpa_supplicant.conf, press <ENTER> to continue"
	read a
	sudo nano /etc/wpa_supplicant/wpa_supplicant.conf
}

# -----------------------------------------------------------------------------------------------------
#
#
install_speech()
{
	// Based on Google speech, by Steven Hickson
    wget –no-check-certificate “http://goo.gl/KrwrBa” -O PiAUISuite.tar.gz
    tar -xvzf PiAUISuite.tar.gz
    cd PiAUISuite/Install/
    sudo ./InstallAUISuite.sh

}

# -----------------------------------------------------------------------------------------------------
# Install the node.js package. Since summer of 2014 there are no distri versions found on nodejs.org
# therefore we switch to node-arm for the latest versions.
#
install_node()
{
	cd $HOMEDIR
#	sudo apt-get upgrade; 
#	sudo apt-get update
    
#	wget http://nodejs.org/dist/v0.10.30/node-v0.10.30-linux-arm-pi.tar.gz
#	tar -xvzf node-v0.10.30-linux-arm-pi.tar.gz
#	node-v0.10.2-linux-arm-pi/bin/node --version
#	NODE_JS_HOME=$HOME/node-v0.10.2-linux-arm-pi ; export NODE_JS_HOME
#	PATH=$PATH:$NODE_JS_HOME/bin
    
    wget http://node-arm.herokuapp.com/node_latest_armhf.deb
    sudo dpkg -i node_latest_armhf.deb
# Check installation
	node -v
# Install add-on packages (Node Package Manager)
    npm install --save express
    # socket.io is not used but ws instead
	npm install --save ws
    npm install --save socket.io
    npm install --save string
#   npm install --save net
#	npm install --save http
    npm install --save connect
    npm install --save serve-static
    npm install --save mysql
    npm install --save async
#	npm install --save child_process
    npm install --save suncalc
    npm install --save strip-json-comments
    npm install --save request
#   npm install --save os
}


# -----------------------------------------------------------------------
# MAIN PROGRAM
#
#
cd $HOMEDIR

printf "This script will upgrade your Raspberry to its latest revision of software.\n"
printf "It will instal MYSQL, PHP and Apache webserver packages which will take\n"
printf "some time to install. \n"
printf "The installer will continue to ask for installation choices until\n"
printf "the user enters Q (for quit)\n\n"
printf "Please press enter to continue or CTRL-C to abort.\n"
printf "\n"
printf "<Press ENTER to start>  "; read a

a=""
isdone="N"

while [ "$isdone" != "Y"  ]
do
	clear
	printf "\nWhat do you like to install\n"
    printf "M: LamPI master node\n"
    printf "S: LamPI Slave node\n"
    printf "Z: Z-Wave gateway\n"
    printf "N: Install Node.js support (done my Master install)\n"
    printf "E: Energy Smart Metering Support\n\n"
    printf "D: Database (MySQL) configuration\n"
    printf "V: Voice support, speech (Development)\n"
    printf "W: Wlan configuration\n\n"
    printf "Q: Quit the installer\n\n"
    printf "Please enter your answer + <ENTER> to continue: "
	read a
    
	if [ "$a" == "M" ]; then
		echo "Installing a Master Node"
   	 	install_linux
		install_wiringpi
        install_node
		install_lampi
		setup_modules
		setup_cron -m   
 	elif [ "$a" == "E" ]; then
		echo "Installing Smart Meter (Energy) support"    
	elif [ "$a" == "N" ]; then
		echo "Installing Node.js"
   	 	install_node
	elif [ "$a" == "S" ]; then
		echo "Installing a LamPI Slave Node"
		install_linux
		install_wiringpi
		install_lampi
		setup_modules
		setup_cron
	elif [ "$a" == "V" ]; then
		echo "Configuring LamPI Voice Support"
		install_speech
	elif [ "$a" == "Z" ]; then
		echo "Installing a Z-Way Gateway Node"
		install_zway
    elif [ "$a" == "B" ]; then
		echo "Installing a Raspbee Gateway Node"
		install_raspbee
    elif [ "$a" == "D" ]; then
    	install_mysql
    elif [ "$a" == "W" ]; then
    	setup_wlan
    elif [ "$a" == "Q" ]; then
		echo "Thank you for installing LamPI"
		isdone="Y"
	else
		echo "Incorrect Input, <$a> Please try again.."
		sleep 2
	fi
done

# -------------------------------------------------------------
# Some more administration to be done for modules
# Make sure that the database is in place
# Make sure that /etc/modprobe.d/raspi.conf contains # in front of i2c lines

echo ""
echo "If you plan to run one database server and have clients connect"
echo "make sure you update bind in /etc/mysql/my.cnf"