#!/bin/sh
#
DAEMONDIR="$HOME"; export DAEMONDIR
SCRIPTDIR="$HOME/scripts"; export SCRIPTDIR
PROGRAM="LamPI-node.js"; export PROGRAM
LOGDIR="$HOME/log"; export LOGDIR
PARAMS=" "; export PARAMS

cd $SCRIPTDIR
BASENAME=`basename "$0"`
echo "starting program: $0, $BASENAME"
#
	LOGFILE="$LOGDIR/$BASENAME.log"; export LOGFILE
#
PID=""; export PID
#
if [ "$1" = "-r" ]; then
	echo "`date`:: Kill previous version of daemons" >> $LOGFILE
	pkill -f "$PROGRAM"
    shift
fi
# If instead of -r (reset) -i (init) is specified, the database.cfg file is reread as well
if [ "$1" = "-i" ]; then
	echo "`date`:: Kill previous version of daemons" >> $LOGFILE
	pkill $PROGRAM
    sleep 2
    echo "`date`:: Start init of database" >> $LOGFILE
    PARAMS=" -i $PARAMS"
fi

#
PID=`ps -eaf | grep "$PROGRAM" | grep -v grep | awk '{print $2}'`
if [ -z "$PID" ]
then
	echo "`/bin/date`:: $BASENAME does not run, Starting $PROGRAM" >> $LOGFILE
	nohup /usr/local/bin/node $HOME/$PROGRAM $PARAMS >> $LOGFILE 2>&1 &
else
	echo "$PID"
fi
