#!/bin/bash
#
#
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/pi:/home/pi/scripts:/home/pi/exe"; export PATH
export DISPLAY=:0
#
EXEDIR="/home/pi/exe"; export EXEDIR
SCRIPTDIR="/home/pi/scripts"; export SCRIPTDIR
SENSOR="rht03-sensor"; export SENSOR
HOSTNAME="255.255.255.255"; export HOSTNAME
PORTNUMBER="5001"; export PORTNUMBER
#
LOGDIR="/home/pi/log"; export LOGDIR
LOGFILE="$LOGDIR/$0.log"; export LOGFILE
PID=""; export PID

# If we specify the -r (restart) argument on the commandline
# we first kill the running program and then start again
if [ "$1" = "-r" ]; then
	echo "`/bin/date`:: Kill previous version of $SENSOR" >> $LOGFILE 2>&1
	pkill $SENSOR
fi

echo "---------------------------------------------------" >> $LOGFILE 2>&1

# Execute the program
# 
cd $EXEDIR
echo "`date`:: Starting $SENSOR" >> $LOGFILE 2>&1
nohup ./$SENSOR -d -b -i -h $HOSTNAME -p $PORTNUMBER >> $LOGFILE 2>&1 &
